#!/bin/bash

# usage: antiflood [time [lines [message]]]

while read -r; do
  if (( SECONDS < ${1-1} )); then
    (( row ++ ))
  else
    SECONDS=0 row=1
  fi
  if (( row < ${2-3} )); then        # less than X lines?  ok, print
    printf "%s\n" "$REPLY"
  elif (( row == ${2-3} )); then     # too many lines, stop flooding
    printf "%s\n" "${3-stop}"
  fi
done
