#!/bin/bash
cd ~/ubase && git pull && make
cd ~/sbase && git pull && make
find ~/ubase ~/sbase -maxdepth 1 -type f -executable -exec ln -vfst /usr/suckless/bin/ {} +
# ln --verbose --force --symbolic --target
